# -*- coding: utf-8 -*-
"""data structure.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xu8Ahi32GqQukNj-hkaAgTEYNfE9XfU6

**list**
"""

pradeep=[1,2,3,4,5]
pradeep[1]=0
print(pradeep)

pradeep=[1,2,3,4,5]
pradeep.append(4)
print(pradeep)

pradeep=[1,2,3,4,5]
pradeep.insert(2,4)
print(pradeep)

pradeep=[1,2,3,4,5]
pradeep.remove(2)
print(pradeep)

pradeep=[1,2,3,4,5]
pradeep.pop(2)
print(pradeep)

pradeep=[1,2,3,4,5]
len("pradeep")
print(pradeep)

pradeep=[1,2,3,4,6,5]
pradeep.sort()
print(pradeep)

pradeep=[1,2,3,4,6,5]
pradeep.reverse()
print(pradeep)

pradeep=[1,2,3,4,6,5]
for i in pradeep:
  print(i)